Preventing modals to close when highlighting text and releasing outside fix#152
edge/wallet pull request #153
Opened 2022-01-24 22:15 UTC by deep34

2022-01-25 09:58 UTC, adamkdean commented
https://github.com/edge/wallet/issues/152

2022-01-26 10:31 UTC, annybs requested changes
The basic logic is sound, but a few changes are needed before we can merge this work.

Please note in addition to the code comments, and with reference to the new [Contributor Guidelines](https://github.com/edge/wallet/blob/develop/CONTRIBUTING.md):

- In this project we do not use semicolons at the end of lines. These should be removed for consistency
- The PR must be rebased onto `develop` branch and the target branch changed to `develop` also

Thanks again for your contribution.

2022-01-26 10:31 UTC, annybs commented on src/components/Modal.vue
> +    },
The Modal component is not responsive to mounting/unmounting events when it is shown/hidden. Modal instances are rendered into the page irrespective of visibility, which is controlled by the `visible` prop.

As such, these event listeners should be toggled by watching the `visible` value instead. Please see [SendModal](https://github.com/edge/wallet/blob/b2cabec879172414ef9721740d40f0d7fa2beb0b/src/components/tx/SendModal.vue#L247-L254) for an example.

(Another, minor point that won't matter after the above change: [beforeUnmount](https://v3.vuejs.org/api/options-lifecycle-hooks.html#beforeunmount) is misspelled)

2022-01-26 10:31 UTC, annybs commented on src/components/Modal.vue
> +          const modalOuter = document.querySelector(".modal-outer");
Please use [a ref](https://v3.vuejs.org/guide/component-template-refs.html) instead of DOM API.

2022-01-28 12:16 UTC, annybs commented
@deep34 Please see #159 reflecting a scope change.

After an internal discussion about UX, we are likely to remove the behaviour of closing modals when clicking outside them.

You are still welcome to complete this PR by resolving my feedback, as there isn't a firm timeline for this change. However, I think it's likely to happen within the next 1 week, so it may not be worth your time to continue working on this. If you agree with that, you can close your PR, otherwise we'll close it for you after that change is implemented.

Thanks again for your contribution either way!

2022-01-28 13:04 UTC, deep34 commented
@annybs No problem, i will close the PR and search for other issues to fix.

2022-01-28 13:04 UTC, closed without merging