Issue/71 export private key
edge/wallet pull request #157
Opened 2022-01-27 15:44 UTC by willgarrett64

For #71

2022-01-27 16:32 UTC, annybs requested changes

2022-01-27 16:32 UTC, annybs commented on src/components/HeaderTools.vue
> +    components: {ArchiveIcon, ChevronDownIcon, CogIcon, KeyIcon, ForgetWallet, ExportKey, LockOpenIcon, LogoutIcon, SupportIcon},
I think this line is getting pretty long, so let's break it up and put each component on its own line - and then alphabetize 👍

2022-01-27 16:32 UTC, annybs commented on src/components/index/ExportModal.vue
> +    ClipboardCopyIcon
Alphabetize

2022-01-27 16:32 UTC, annybs commented on src/components/index/ExportModal.vue
> +    }),
Change this to `...mapState(['address']),` as we don't need to explicitly alias the prop. See: https://vuex.vuejs.org/guide/state.html#the-mapstate-helper

2022-01-27 16:32 UTC, annybs commented on src/components/index/ExportModal.vue
> +      this.privateKey = ''
Reset `passwordError` as well

2022-01-27 16:32 UTC, annybs commented on src/components/index/ExportModal.vue
> +      this.privateKey = await storage.getPrivateKey(this.password);
Remove EOL semicolon, we don't use them in this project.

(I'm aware the existing code is a bit inconsistent about this, I'm counting on adding linting at some point to help with this. At the very least, that's the direction we're moving)

2022-01-27 16:32 UTC, annybs commented on src/components/index/ExportModal.vue
> +      <div v-else class="px-24 pt-5 pb-30">
The top border for the footer block is lost here. For continuity, preserve all CSS classes from the original `v-if` (with allowances for padding changes)

2022-01-27 21:20 UTC, willgarrett64 commented on src/components/index/ExportModal.vue
> +      <div v-else class="px-24 pt-5 pb-30">
I conserved all except md:grid-cols-2 to keep the button centralised. Not sure exactly what all these tailwind classes do, but it seemed to do the trick!

2022-01-28 09:09 UTC, annybs approved these changes
LGTM. Go ahead and merge, and it should automatically deploy to testnet. Ask @adamkdean to have a look once it's up in case he has any language or design feedback.

2022-01-28 09:21 UTC, merged