feat: add unlock and release buttons to stake table
edge/wallet pull request #181
Opened 2022-02-07 11:03 UTC by willgarrett64

Combine issues: #80 #81 #82

2022-02-09 17:49 UTC, willgarrett64 commented
@annybs - There is one bit in ReleaseStakeModal that I would like your help with:
https://github.com/edge/wallet/blob/b489eb6bdddd67bb24dd1192caefaee8da70fc0e/src/components/stakes/ReleaseStakeModal.vue#L251-L252
I want to get get use `this.releaseFeePc` rather than a hard coded 25% in the confirm phrase. I tried multiple times to get this to work, moving to computed values for example, but couldn't get it to work. I did try reading vuelidate docs, but still no luck...

2022-02-10 14:52 UTC, annybs requested changes

2022-02-10 14:52 UTC, annybs commented on src/components/stakes/CreateStakeModal.vue
> +                  id="pass-step"
Use `id="password"` here and on the label

2022-02-10 15:05 UTC, willgarrett64 commented on src/views/Staking.vue
> +      stakeToUnlock: null,
I realised this one as I was drifting of to sleep around midnight last night. Woke up in the morning and said to my wife "there is a fix I need to do that I remembered last night, but I can't quite remember...". I know you'd find it though.

2022-02-10 16:24 UTC, annybs approved these changes

2022-02-10 17:29 UTC, merged